version: "3"

tasks:
  install:
    cmd: uv sync --all-groups
    desc: Install dependencies

  format:
    cmd: uv run ruff format .
    desc: Format Python code with ruff

  check:
    cmd: uv run ruff check --fix .
    desc: Check Python code with ruff and auto-fix issues

  test:
    cmd: uv run pytest tests/ --cov=pragma_cli --cov-report=term-missing {{.CLI_ARGS}}
    desc: Run all tests with coverage
