version: "3"

tasks:
  install:
    desc: Install dependencies
    cmd: uv sync --all-groups

  format:
    desc: Format code
    cmd: uv run ruff format .

  check:
    desc: Lint and type check
    cmds:
      - uv run ruff check --fix .
      - uvx ty check

  test:
    desc: Run tests
    cmd: uv run pytest tests/ --cov=pragma_cli --cov-report=term-missing {{.CLI_ARGS}}
